services:
  app:
    build: .
    container_name: habitlog-app
    ports:
      - "${SERVER_PORT:-8082}:8082"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./build.gradle:/app/build.gradle
      - ./settings.gradle:/app/settings.gradle
    restart: unless-stopped

  db:
    image: mysql:8
    container_name: habitlog-db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: