server:
  port: ${SERVER_PORT:8083}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:habitlog_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
    show-sql: ${DB_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${DB_FORMAT_SQL:true}
        use_sql_comments: ${DB_USE_SQL_COMMENTS:true}
        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  paths-to-exclude:
    - /actuator/**
    - /error

logging:
  level:
    org.hibernate.SQL: ${LOG_LEVEL_SQL:INFO}
    org.hibernate.type.descriptor.sql: ${LOG_LEVEL_TYPE:INFO}
    org.springframework.web: ${LOG_LEVEL_WEB:INFO}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always